upstream auth_backend      { server auth-service:80; }
upstream passenger_backend { server passenger-service:80; }
upstream route_backend     { server route-service:80; }
upstream booking_backend   { server booking-service:80; }
upstream ticket_backend    { server ticket-service:80; }

server {
    listen 80;
    server_name _;

    location /health {
        return 200 '{"status":"ok","platform":"intercity237","version":"1.0"}';
        add_header Content-Type application/json;
    }

    location ~ ^/(login|register|logout|forgot_password|reset_password)\.php {
        proxy_pass http://auth_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Service auth-service;
    }

    location ~ ^/(profile|my-bookings)\.php {
        proxy_pass http://passenger_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Service passenger-service;

        
    }

    location /admin/ {
        proxy_pass http://passenger_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Service passenger-service;
    }

    location ~ ^/(checkout|bookings?)\.php {
        proxy_pass http://booking_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Service booking-service;
    }

    location ~ ^/(ticket|scan)\.php {
        proxy_pass http://ticket_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Service ticket-service;
    }

    location /api/ {
        proxy_pass http://route_backend/api.php;
        proxy_set_header Host $host;
        proxy_set_header X-Service route-service;
        add_header Access-Control-Allow-Origin *;
    }

    location ~* \.(css|js|png|jpg|ico|woff2?)$ {
        proxy_pass http://auth_backend;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://booking_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
