apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: intercity237
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: intercity237
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mariadb
        image: mariadb:11
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: intercity237
        - name: MYSQL_USER
          value: intercity237
        - name: MYSQL_PASSWORD
          value: Intercity2372026
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
          initialDelaySeconds: 30
          periodSeconds: 15
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: intercity237
spec:
  selector:
    app: db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
