-- ============================================================
-- CIMENCAM HR Portal — Database Schema
-- Course: BSC-SE3230 Web Application Development
-- Instructor: Engr. Tanwi Nkiamboh
-- ============================================================
-- NOTE: Use setup.php to initialize the database automatically.
-- This file is for reference / manual setup.
-- ============================================================

CREATE DATABASE IF NOT EXISTS `cimancam`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `cimancam`;

-- -----------------------------------------------------------
-- Table: departments
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS `departments` (
    `id`          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name`        VARCHAR(100) NOT NULL,
    `description` TEXT,
    `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO `departments` (`name`, `description`) VALUES
('Production',            'Cement production and manufacturing operations'),
('Quality Control',       'Product quality assurance and testing'),
('Logistics & Transport', 'Distribution, transport, and supply chain management'),
('Finance & Accounting',  'Financial management, payroll, and accounting'),
('Human Resources',       'Personnel management, recruitment, and training'),
('Information Technology','IT infrastructure, systems, and support'),
('Sales & Marketing',     'Commercial activities and market development'),
('Procurement',           'Purchasing, supplier management, and contracts'),
('Maintenance',           'Equipment maintenance and engineering services'),
('Administration',        'General administration and executive management');

-- -----------------------------------------------------------
-- Table: users
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
    `id`            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `full_name`     VARCHAR(200) NOT NULL,
    `home_address`  TEXT,
    `email`         VARCHAR(150) NOT NULL,
    `phone`         VARCHAR(30),
    `username`      VARCHAR(100) NOT NULL,
    `password`      VARCHAR(255) NOT NULL,         -- bcrypt hash
    `role`          ENUM('superadmin','admin','employee') NOT NULL DEFAULT 'employee',
    `department_id` INT UNSIGNED,
    `reset_token`   VARCHAR(255),
    `reset_expiry`  DATETIME,
    `created_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uq_email`    (`email`),
    UNIQUE KEY `uq_username` (`username`),
    FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Default superadmin: username=superadmin / password=Admin@1234
-- (Hash generated by setup.php — do not hardcode plain text)

-- -----------------------------------------------------------
-- Table: department_records  (10 fields per exam requirement)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS `department_records` (
    `id`            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `department_id` INT UNSIGNED NOT NULL,
    `employee_id`   VARCHAR(50)  DEFAULT NULL,   -- Field 1
    `full_name`     VARCHAR(200) DEFAULT NULL,   -- Field 2
    `position`      VARCHAR(150) DEFAULT NULL,   -- Field 3
    `salary`        VARCHAR(50)  DEFAULT NULL,   -- Field 4
    `start_date`    DATE         DEFAULT NULL,   -- Field 5
    `status`        ENUM('Active','On Leave','Suspended','Resigned') DEFAULT 'Active', -- Field 6
    `phone`         VARCHAR(30)  DEFAULT NULL,   -- Field 7
    `email`         VARCHAR(150) DEFAULT NULL,   -- Field 8
    `address`       TEXT         DEFAULT NULL,   -- Field 9
    `remarks`       TEXT         DEFAULT NULL,   -- Field 10
    `created_by`    INT UNSIGNED DEFAULT NULL,
    `created_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`department_id`) REFERENCES `departments`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;
